services:
  postgres:
    image: debezium/postgres:16
    container_name: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c 'wal_level=logical'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./DB_SQL:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    networks:
      - sport_network

  producer_history_strava:
    build:
      context: ./scripts_import_data
      dockerfile: Dockerfile
    container_name: producer_history_strava
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sport_network

  dbt:
    build:
      context: ./dbt
      dockerfile: Dockerfile
    container_name: elt_dbt
    depends_on:
      producer_history_strava:
        condition: service_completed_successfully
    environment:
      - DBT_PROFILES_DIR=/app/profiles
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=sport_activities_db
      - POSTGRES_SCHEMA=public
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
    volumes:
      - ./dbt:/app
    networks:
      - sport_network

  superset:
    image: apache/superset:latest-dev
    container_name: superset
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      SUPERSET_LOAD_EXAMPLES: "no"
      EXTRA_PIP_PACKAGES: psycopg2-binary
    ports:
      - "8088:8088"
    volumes:
      - superset_data:/app/superset_home
      - ./export.zip:/app/export.zip
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command: >
      /bin/sh -c "
      pip install psycopg2-binary &&
      superset db upgrade &&
      superset fab create-admin --username admin --firstname Admin --lastname User --email admin@example.com --password admin &&
      superset init &&
      superset set-database-uri -d sport_activities -u postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} &&
      superset import-dashboards -p export.zip -u admin &&
      superset run -h 0.0.0.0 -p 8088
      "
    networks:
      - sport_network

  strava_sender:
    build:
      context: ./slack
      dockerfile: Dockerfile
    container_name: slack_sender
    environment:
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    depends_on:
      dbt:
        condition: service_completed_successfully
    networks:
      - sport_network

volumes:
  postgres_data:
  superset_data:
networks:
  sport_network:
    driver: bridge